INSERT INTO COLORS (red, green, blue, name) VALUES(93, 138, 168, 'Air Force Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(240, 248, 255, 'Alice Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(227, 38, 54, 'Alizarin');
INSERT INTO COLORS (red, green, blue, name) VALUES(229, 43, 80, 'Amaranth');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 191, 0, 'Amber');
INSERT INTO COLORS (red, green, blue, name) VALUES(164, 198, 57, 'Android Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(141, 182, 0, 'Apple Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(251, 206, 177, 'Apricot');
INSERT INTO COLORS (red, green, blue, name) VALUES(127, 255, 212, 'Aquamarine');
INSERT INTO COLORS (red, green, blue, name) VALUES(75, 83, 32, 'Army Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(59, 68, 75, 'Arsenic');
INSERT INTO COLORS (red, green, blue, name) VALUES(233, 214, 107, 'Arylide Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(178, 190, 181, 'Ash Grey');
INSERT INTO COLORS (red, green, blue, name) VALUES(135, 169, 107, 'Asparagus');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 153, 102, 'Atomic Tangerine');
INSERT INTO COLORS (red, green, blue, name) VALUES(109, 53, 26, 'Auburn');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 127, 255, 'Azure');
INSERT INTO COLORS (red, green, blue, name) VALUES(137, 207, 240, 'Baby Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(161, 202, 241, 'Baby Blue Eyes');
INSERT INTO COLORS (red, green, blue, name) VALUES(244, 194, 194, 'Baby Pink');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 209, 42, 'Banana Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(132, 132, 130, 'Battleship Grey');
INSERT INTO COLORS (red, green, blue, name) VALUES(152, 119, 123, 'Bazaar');
INSERT INTO COLORS (red, green, blue, name) VALUES(245, 245, 220, 'Beige');
INSERT INTO COLORS (red, green, blue, name) VALUES(61, 43, 31, 'Bistre');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 0, 0, 'Black');
INSERT INTO COLORS (red, green, blue, name) VALUES(49, 140, 231, 'Bleu De France');
INSERT INTO COLORS (red, green, blue, name) VALUES(250, 240, 190, 'Blond');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 0, 255, 'Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(222, 93, 131, 'Blush');
INSERT INTO COLORS (red, green, blue, name) VALUES(121, 68, 59, 'Bole');
INSERT INTO COLORS (red, green, blue, name) VALUES(204, 0, 0, 'Boston University Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(181, 166, 66, 'Brass');
INSERT INTO COLORS (red, green, blue, name) VALUES(102, 255, 0, 'Bright Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(191, 148, 228, 'Bright Lavender');
INSERT INTO COLORS (red, green, blue, name) VALUES(195, 33, 72, 'Bright Maroon');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 0, 127, 'Bright Pink');
INSERT INTO COLORS (red, green, blue, name) VALUES(8, 232, 222, 'Bright Turquoise');
INSERT INTO COLORS (red, green, blue, name) VALUES(209, 159, 232, 'Bright Ube');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 66, 37, 'British Racing Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(205, 127, 50, 'Bronze');
INSERT INTO COLORS (red, green, blue, name) VALUES(150, 75, 0, 'Brown');
INSERT INTO COLORS (red, green, blue, name) VALUES(252, 193, 204, 'Bubble Gum');
INSERT INTO COLORS (red, green, blue, name) VALUES(231, 254, 255, 'Bubbles');
INSERT INTO COLORS (red, green, blue, name) VALUES(240, 220, 130, 'Buff');
INSERT INTO COLORS (red, green, blue, name) VALUES(128, 0, 32, 'Burgundy');
INSERT INTO COLORS (red, green, blue, name) VALUES(222, 184, 135, 'Burlywood');
INSERT INTO COLORS (red, green, blue, name) VALUES(204, 85, 0, 'Burnt Orange');
INSERT INTO COLORS (red, green, blue, name) VALUES(233, 116, 81, 'Burnt Sienna');
INSERT INTO COLORS (red, green, blue, name) VALUES(138, 51, 36, 'Burnt Umber');
INSERT INTO COLORS (red, green, blue, name) VALUES(189, 51, 164, 'Byzantine');
INSERT INTO COLORS (red, green, blue, name) VALUES(112, 41, 99, 'Byzantium');
INSERT INTO COLORS (red, green, blue, name) VALUES(83, 104, 120, 'Cadet');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 107, 60, 'Cadmium Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(237, 135, 45, 'Cadmium Orange');
INSERT INTO COLORS (red, green, blue, name) VALUES(227, 0, 34, 'Cadmium Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(163, 193, 173, 'Cambridge Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(120, 134, 107, 'Camouflage Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 239, 0, 'Canary Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 8, 0, 'Candy Apple Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(196, 30, 58, 'Cardinal');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 204, 153, 'Caribbean Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(150, 0, 24, 'Carmine');
INSERT INTO COLORS (red, green, blue, name) VALUES(153, 186, 227, 'Carolina Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(237, 145, 33, 'Carrot Orange');
INSERT INTO COLORS (red, green, blue, name) VALUES(146, 161, 207, 'Ceil');
INSERT INTO COLORS (red, green, blue, name) VALUES(172, 225, 175, 'Celadon');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 123, 167, 'Cerulean');
INSERT INTO COLORS (red, green, blue, name) VALUES(42, 82, 190, 'Cerulean Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(160, 120, 90, 'Chamoisee');
INSERT INTO COLORS (red, green, blue, name) VALUES(247, 231, 206, 'Champagne');
INSERT INTO COLORS (red, green, blue, name) VALUES(54, 69, 79, 'Charcoal');
INSERT INTO COLORS (red, green, blue, name) VALUES(223, 255, 0, 'Chartreuse');
INSERT INTO COLORS (red, green, blue, name) VALUES(222, 49, 99, 'Cherry');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 183, 197, 'Cherry Blossom Pink');
INSERT INTO COLORS (red, green, blue, name) VALUES(205, 92, 92, 'Chestnut');
INSERT INTO COLORS (red, green, blue, name) VALUES(123, 63, 0, 'Chocolate');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 167, 0, 'Chrome Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(152, 129, 123, 'Cinereous');
INSERT INTO COLORS (red, green, blue, name) VALUES(227, 66, 52, 'Cinnabar');
INSERT INTO COLORS (red, green, blue, name) VALUES(210, 105, 30, 'Cinnamon');
INSERT INTO COLORS (red, green, blue, name) VALUES(228, 208, 10, 'Citrine');
INSERT INTO COLORS (red, green, blue, name) VALUES(251, 204, 231, 'Classic Rose');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 255, 111, 'Clover');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 71, 171, 'Cobalt');
INSERT INTO COLORS (red, green, blue, name) VALUES(155, 221, 255, 'Columbia Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 46, 99, 'Cool Black');
INSERT INTO COLORS (red, green, blue, name) VALUES(140, 146, 172, 'Cool Grey');
INSERT INTO COLORS (red, green, blue, name) VALUES(184, 115, 51, 'Copper');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 56, 0, 'Coquelicot');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 127, 80, 'Coral');
INSERT INTO COLORS (red, green, blue, name) VALUES(137, 63, 69, 'Cordovan');
INSERT INTO COLORS (red, green, blue, name) VALUES(251, 236, 93, 'Corn');
INSERT INTO COLORS (red, green, blue, name) VALUES(179, 27, 27, 'Cornell Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(100, 149, 237, 'Cornflower Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 248, 220, 'Cornsilk');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 253, 208, 'Cream');
INSERT INTO COLORS (red, green, blue, name) VALUES(220, 20, 60, 'Crimson');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 255, 255, 'Cyan');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 255, 49, 'Daffodil');
INSERT INTO COLORS (red, green, blue, name) VALUES(240, 225, 48, 'Dandelion');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 0, 139, 'Dark Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(101, 67, 33, 'Dark Brown');
INSERT INTO COLORS (red, green, blue, name) VALUES(93, 57, 84, 'Dark Byzantium');
INSERT INTO COLORS (red, green, blue, name) VALUES(164, 0, 0, 'Dark Candy Apple Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(8, 69, 126, 'Dark Cerulean');
INSERT INTO COLORS (red, green, blue, name) VALUES(152, 105, 96, 'Dark Chestnut');
INSERT INTO COLORS (red, green, blue, name) VALUES(205, 91, 69, 'Dark Coral');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 139, 139, 'Dark Cyan');
INSERT INTO COLORS (red, green, blue, name) VALUES(184, 134, 11, 'Dark Goldenrod');
INSERT INTO COLORS (red, green, blue, name) VALUES(1, 50, 32, 'Dark Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(26, 36, 33, 'Dark Jungle Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(189, 183, 107, 'Dark Khaki');
INSERT INTO COLORS (red, green, blue, name) VALUES(72, 60, 50, 'Dark Lava');
INSERT INTO COLORS (red, green, blue, name) VALUES(115, 79, 150, 'Dark Lavender');
INSERT INTO COLORS (red, green, blue, name) VALUES(139, 0, 139, 'Dark Magenta');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 51, 102, 'Dark Midnight Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(85, 107, 47, 'Dark Olive Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 140, 0, 'Dark Orange');
INSERT INTO COLORS (red, green, blue, name) VALUES(119, 158, 203, 'Dark Pastel Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(3, 192, 60, 'Dark Pastel Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(150, 111, 214, 'Dark Pastel Purple');
INSERT INTO COLORS (red, green, blue, name) VALUES(194, 59, 34, 'Dark Pastel Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(231, 84, 128, 'Dark Pink');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 51, 153, 'Dark Powder Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(135, 38, 87, 'Dark Raspberry');
INSERT INTO COLORS (red, green, blue, name) VALUES(233, 150, 122, 'Dark Salmon');
INSERT INTO COLORS (red, green, blue, name) VALUES(86, 3, 25, 'Dark Scarlet');
INSERT INTO COLORS (red, green, blue, name) VALUES(60, 20, 20, 'Dark Sienna');
INSERT INTO COLORS (red, green, blue, name) VALUES(47, 79, 79, 'Dark Slate Gray');
INSERT INTO COLORS (red, green, blue, name) VALUES(23, 114, 69, 'Dark Spring Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(145, 129, 81, 'Dark Tan');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 168, 18, 'Dark Tangerine');
INSERT INTO COLORS (red, green, blue, name) VALUES(204, 78, 92, 'Dark Terra Cotta');
INSERT INTO COLORS (red, green, blue, name) VALUES(148, 0, 211, 'Dark Violet');
INSERT INTO COLORS (red, green, blue, name) VALUES(85, 85, 85, 'Dark Grey');
INSERT INTO COLORS (red, green, blue, name) VALUES(21, 96, 189, 'Denim');
INSERT INTO COLORS (red, green, blue, name) VALUES(193, 154, 107, 'Desert');
INSERT INTO COLORS (red, green, blue, name) VALUES(237, 201, 175, 'Desert Sand');
INSERT INTO COLORS (red, green, blue, name) VALUES(105, 105, 105, 'Dim Gray');
INSERT INTO COLORS (red, green, blue, name) VALUES(133, 187, 101, 'Dollar Bill');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 0, 156, 'Duke Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(225, 169, 95, 'Earth Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(97, 64, 81, 'Eggplant');
INSERT INTO COLORS (red, green, blue, name) VALUES(80, 200, 120, 'Emerald');
INSERT INTO COLORS (red, green, blue, name) VALUES(229, 170, 112, 'Fawn');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 28, 0, 'Ferrari Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(206, 22, 32, 'Fire Engine Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(178, 34, 34, 'Firebrick');
INSERT INTO COLORS (red, green, blue, name) VALUES(226, 88, 34, 'Flame');
INSERT INTO COLORS (red, green, blue, name) VALUES(252, 142, 172, 'Flamingo Pink');
INSERT INTO COLORS (red, green, blue, name) VALUES(247, 233, 142, 'Flavescent');
INSERT INTO COLORS (red, green, blue, name) VALUES(1, 68, 33, 'Forest Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(228, 155, 15, 'Gamboge');
INSERT INTO COLORS (red, green, blue, name) VALUES(248, 248, 255, 'Ghost White');
INSERT INTO COLORS (red, green, blue, name) VALUES(96, 130, 182, 'Glaucous');
INSERT INTO COLORS (red, green, blue, name) VALUES(153, 101, 21, 'Golden Brown');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 223, 0, 'Golden Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(218, 165, 32, 'Goldenrod');
INSERT INTO COLORS (red, green, blue, name) VALUES(128, 128, 128, 'Gray');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 128, 0, 'Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(113, 166, 210, 'Iceberg');
INSERT INTO COLORS (red, green, blue, name) VALUES(252, 247, 94, 'Icterine');
INSERT INTO COLORS (red, green, blue, name) VALUES(178, 236, 93, 'Inchworm');
INSERT INTO COLORS (red, green, blue, name) VALUES(19, 136, 8, 'India Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(205, 92, 92, 'Indian Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(227, 168, 87, 'Indian Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 47, 167, 'International Klein Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 255, 240, 'Ivory');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 168, 107, 'Jade');
INSERT INTO COLORS (red, green, blue, name) VALUES(215, 59, 62, 'Jasper');
INSERT INTO COLORS (red, green, blue, name) VALUES(195, 176, 145, 'Khaki');
INSERT INTO COLORS (red, green, blue, name) VALUES(181, 126, 220, 'Lavender');
INSERT INTO COLORS (red, green, blue, name) VALUES(204, 204, 255, 'Lavender Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 240, 245, 'Lavender Blush');
INSERT INTO COLORS (red, green, blue, name) VALUES(196, 195, 208, 'Lavender Gray');
INSERT INTO COLORS (red, green, blue, name) VALUES(124, 252, 0, 'Lawn Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 247, 0, 'Lemon');
INSERT INTO COLORS (red, green, blue, name) VALUES(191, 255, 0, 'Lime');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 0, 255, 'Magenta');
INSERT INTO COLORS (red, green, blue, name) VALUES(192, 64, 0, 'Mahogany');
INSERT INTO COLORS (red, green, blue, name) VALUES(128, 0, 0, 'Maroon');
INSERT INTO COLORS (red, green, blue, name) VALUES(25, 25, 112, 'Midnight Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(62, 180, 137, 'Mint');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 219, 88, 'Mustard');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 0, 128, 'Navy Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(204, 119, 34, 'Ochre');
INSERT INTO COLORS (red, green, blue, name) VALUES(128, 128, 0, 'Olive');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 127, 0, 'Orange');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 33, 71, 'Oxford Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(174, 198, 207, 'Pastel Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(130, 105, 83, 'Pastel Brown');
INSERT INTO COLORS (red, green, blue, name) VALUES(207, 207, 196, 'Pastel Gray');
INSERT INTO COLORS (red, green, blue, name) VALUES(119, 221, 119, 'Pastel Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(244, 154, 194, 'Pastel Magenta');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 179, 71, 'Pastel Orange');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 209, 220, 'Pastel Pink');
INSERT INTO COLORS (red, green, blue, name) VALUES(179, 158, 181, 'Pastel Purple');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 105, 97, 'Pastel Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(203, 153, 201, 'Pastel Violet');
INSERT INTO COLORS (red, green, blue, name) VALUES(253, 253, 150, 'Pastel Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 229, 180, 'Peach');
INSERT INTO COLORS (red, green, blue, name) VALUES(209, 226, 49, 'Pear');
INSERT INTO COLORS (red, green, blue, name) VALUES(240, 234, 214, 'Pearl');
INSERT INTO COLORS (red, green, blue, name) VALUES(230, 226, 0, 'Peridot');
INSERT INTO COLORS (red, green, blue, name) VALUES(1, 121, 111, 'Pine Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 192, 203, 'Pink');
INSERT INTO COLORS (red, green, blue, name) VALUES(147, 197, 114, 'Pistachio');
INSERT INTO COLORS (red, green, blue, name) VALUES(229, 228, 226, 'Platinum');
INSERT INTO COLORS (red, green, blue, name) VALUES(142, 69, 133, 'Plum');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 90, 54, 'Portland Orange');
INSERT INTO COLORS (red, green, blue, name) VALUES(112, 28, 28, 'Prune');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 117, 24, 'Pumpkin');
INSERT INTO COLORS (red, green, blue, name) VALUES(105, 53, 156, 'Purple Heart');
INSERT INTO COLORS (red, green, blue, name) VALUES(227, 11, 92, 'Raspberry');
INSERT INTO COLORS (red, green, blue, name) VALUES(130, 102, 68, 'Raw Umber');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 0, 0, 'Red');
INSERT INTO COLORS (red, green, blue, name) VALUES(65, 72, 51, 'Rifle Green');
INSERT INTO COLORS (red, green, blue, name) VALUES(101, 0, 11, 'Rosewood');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 35, 102, 'Royal Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(224, 17, 95, 'Ruby');
INSERT INTO COLORS (red, green, blue, name) VALUES(183, 65, 14, 'Rust');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 103, 0, 'Safety Orange');
INSERT INTO COLORS (red, green, blue, name) VALUES(244, 196, 48, 'Saffron');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 140, 105, 'Salmon');
INSERT INTO COLORS (red, green, blue, name) VALUES(194, 178, 128, 'Sand');
INSERT INTO COLORS (red, green, blue, name) VALUES(150, 113, 23, 'Sand Dune');
INSERT INTO COLORS (red, green, blue, name) VALUES(236, 213, 64, 'Sandstorm');
INSERT INTO COLORS (red, green, blue, name) VALUES(8, 37, 103, 'Sapphire');
INSERT INTO COLORS (red, green, blue, name) VALUES(50, 20, 20, 'Seal Brown');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 245, 238, 'Seashell');
INSERT INTO COLORS (red, green, blue, name) VALUES(112, 66, 20, 'Sepia');
INSERT INTO COLORS (red, green, blue, name) VALUES(138, 121, 93, 'Shadow');
INSERT INTO COLORS (red, green, blue, name) VALUES(192, 192, 192, 'Silver');
INSERT INTO COLORS (red, green, blue, name) VALUES(203, 65, 11, 'Sinopia');
INSERT INTO COLORS (red, green, blue, name) VALUES(135, 206, 235, 'Sky Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(207, 113, 175, 'Sky Magenta');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 250, 250, 'Snow');
INSERT INTO COLORS (red, green, blue, name) VALUES(167, 252, 0, 'Spring Bud');
INSERT INTO COLORS (red, green, blue, name) VALUES(70, 130, 180, 'Steel Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(228, 217, 111, 'Straw');
INSERT INTO COLORS (red, green, blue, name) VALUES(250, 214, 165, 'Sunset');
INSERT INTO COLORS (red, green, blue, name) VALUES(242, 133, 0, 'Tangerine');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 128, 128, 'Teal');
INSERT INTO COLORS (red, green, blue, name) VALUES(226, 114, 91, 'Terra Cotta');
INSERT INTO COLORS (red, green, blue, name) VALUES(238, 230, 0, 'Titanium Yellow');
INSERT INTO COLORS (red, green, blue, name) VALUES(0, 117, 94, 'Tropical Rain Forest');
INSERT INTO COLORS (red, green, blue, name) VALUES(48, 213, 200, 'Turquoise');
INSERT INTO COLORS (red, green, blue, name) VALUES(18, 10, 255, 'Ultramarine');
INSERT INTO COLORS (red, green, blue, name) VALUES(91, 146, 229, 'United Nations Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(243, 229, 171, 'Vanilla');
INSERT INTO COLORS (red, green, blue, name) VALUES(143, 0, 255, 'Violet');
INSERT INTO COLORS (red, green, blue, name) VALUES(245, 222, 179, 'Wheat');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 255, 255, 'White');
INSERT INTO COLORS (red, green, blue, name) VALUES(245, 245, 245, 'White Smoke');
INSERT INTO COLORS (red, green, blue, name) VALUES(115, 134, 120, 'Xanadu');
INSERT INTO COLORS (red, green, blue, name) VALUES(15, 77, 146, 'Yale Blue');
INSERT INTO COLORS (red, green, blue, name) VALUES(255, 255, 0, 'Yellow');