export const CURRENT_CARD_SWIPE_LEFT = 'CURRENT_CARD_SWIPE_LEFT';
export const CURRENT_CARD_SWIPE_RIGHT = 'CURRENT_CARD_SWIPE_RIGHT';
export const CURRENT_IMAGE_DOWN = 'CURRENT_IMAGE_DOWN';
export const CURRENT_IMAGE_UP = 'CURRENT_IMAGE_UP';
export const QUEUE_CHANGE = 'QUEUE_CHANGE';
export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
